### DISCUSSION TITLE
[Question] Question title自己训练的GO2代码部署

### DISCUSSION THREAD

**Discussion by HaodongHuang-W** [fan-ziqi/rl_sar#97] [Q&A]

**Comment by HaodongHuang-W** [comment]
哥，我在用你的代码的过程中，我在go2的model下面新建了代码

![Image](https://github.com/user-attachments/assets/87f17a2e-a149-4340-8fd2-940c14873843)

![Image](https://github.com/user-attachments/assets/11a23a78-34ee-4909-87b7-a287d42a9809)

![Image](https://github.com/user-attachments/assets/d0a6ba56-b50b-40b8-890e-81844fd02a5b)
sim2sim的时候一直报错，然后其他的himloco都可以，就我的这个不可以，报错如下

![Image](https://github.com/user-attachments/assets/0f13d8a8-9062-4447-a827-9bbd128cbd66)
```yaml
go2/BYOL:
  model_name: "byol.pt"
  framework: "isaacgym"
  dt: 0.005
  decimation: 4
  num_observations: 45
#   observations: ["commands", "ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations_history: [0, 1, 2, 3, 4, 5,6,7,8,9]  # 0 is the latest observation
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [40, 40, 40,
          40, 40, 40,
          40, 40, 40,
          40, 40, 40]
  rl_kd: [1, 1, 1,
          1, 1, 1,
          1, 1, 1,
          1, 1, 1]
  fixed_kp: [60, 60, 60,
             60, 60, 60,
             60, 60, 60,
             60, 60, 60]
  fixed_kd: [5, 5, 5,
             5, 5, 5,
             5, 5, 5,
             5, 5, 5]
  num_of_dofs: 12
  action_scale: [0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25,
                 0.125, 0.25, 0.25]
  wheel_indices: []
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25]
#   torque_limits: [33.5, 33.5, 33.5,
#                   33.5, 33.5, 33.5,
#                   33.5, 33.5, 33.5,
#                   33.5, 33.5, 33.5]

  torque_limits: [23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5,
                  23.5, 23.5, 23.5]

  default_dof_pos: [ 0.1000, 0.8000, -1.5000,
                    -0.1000, 0.8000, -1.5000,
                     0.1000, 1.0000, -1.5000,
                    -0.1000, 1.0000, -1.5000]
  # joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
  #                          "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
  #                          "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
  #                          "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]

  joint_controller_names: ["FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller"]
#   command_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]
#   state_mapping: [3, 4, 5, 0, 1, 2, 9, 10, 11, 6, 7, 8]
  command_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  state_mapping: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
```
